---
name: (( merge ))

director_uuid: (( merge ))

releases:
  - name: dummy
    version: latest

networks:
- name: cf1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
    static:
    - 10.244.0.10
  - cloud_properties:
      name: random
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
    static:
    - 10.244.0.14
  - cloud_properties:
      name: random
    range: 10.244.0.16/30
    reserved:
    - 10.244.0.17
    static:
    - 10.244.0.18
  - cloud_properties:
      name: random
    range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    static:
    - 10.244.0.22
  - cloud_properties:
      name: random
    range: 10.244.0.24/30
    reserved:
    - 10.244.0.25
    static:
    - 10.244.0.26

jobs:
  - name: dummy_z1
    template: dummy
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips:
          - 10.244.0.2
    properties:
      network_name: cf1

properties:
  warden:
    kernel_network_tuning_enabled: true

meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

compilation:
  workers: 1
  network: cf1
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

resource_pools:
  - name: medium_z1
    network: cf1
    stemcell: (( meta.stemcell ))
    cloud_properties:
      name: random
